#!/bin/bash
# Bash Script for Hide Phishing URL Created by AppShakti Bangla

# Check if jq is installed
if ! command -v jq &> /dev/null; then
    echo "Installing jq..."
    pkg install jq -y
fi

if ! command -v curl &> /dev/null; then
    echo "curl is not installed, installing now..."
    pkg install curl -y
fi

clear
echo -e "       \e[1;93m      🔥 Powered by App Shakti Bangla 🔥      \e[0m\n"
echo -e "       \e[1;92m=========================================\e[0m\n\n"
echo -e " \e[5m         \e[25m \e[1;91m [\e[1;96m*\e[1;91m] \e[1;93mDeveloper  \e[1;97m=  \e[4m\e[1;92mMahadeb Ruidas  \e[0m\n"
echo -e " \e[1m          \e[1;91m [\e[1;96m*\e[1;91m] \e[1;94mTelegram   \e[5m\e[1;97m=   \e[1;92m@masterdas000  \e[0m\n"
echo -e ""
echo -e "\e[95m <======================|M|A|H|A|D|E|B|=====================>"
echo -e "" 
echo -e ' \e[91m[\e[92m★\e[91m] \e[32mPaste Phishing URL/Link here \e[96m(http or https):\e[0m '
echo -en "\e[32m =>\e[0m "
read inpurl
echo -e ""
short=$(curl -s http://tinyurl.com/api-create.php?url=$inpurl)
shorter=${short#https://}
echo -e "\e[96mhttps://m.facebook.com
https://m.facebook.com/hacked
https://www.google.com
https://www.instagram.com
https://m.youtube.com
https://youtu.be\e[0m"
echo -e "\e[91m[\e[92m*\e[91m]\e[93m\e[1m Domain to mask the Phishing URL \e[21m\e[0m:"
echo -en "\e[32m =>\e[0m "
read mask
echo -e ""
echo -e ""
echo -e ' \e[21m\e[0m\e[96mfolowers, like, free-money, free-insta-followers, happy'
echo -en "\e[91m[\e[92m*\e[91m]\e[93m\e[1m choose one option :\e[0m"
read words
echo -e ""
echo -e ""
echo -e " \e[32m+=>\e[94m Processing Short and Masking URL ..........\e[0m"
sleep 3
echo -e " \e[32m+=>\e[95mMasking Link by Credit by AppShakti Bangla.......\e[0m\n"
sleep 5
echo -e ""
final=$mask-$words@$shorter
echo -e " \e[91m[\e[92m★\e[91m] \e[93m Redy Your Masking URL/Link:\e[1;92m ${final} \e[0m\n"
echo -e ""
